version: "3.8"
services:
  road-recommendation-redis:
    container_name: road-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: parkhyunwoo/road-recommendation-redis
    ports:
    - "6379:6379"
  road-recommendation-database:
    container_name: road-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: parkhyunwoo/road-recommendation-database
    environment:
      - MYSQL_DATABASE=road-recommendation
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
    - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"